"""
Unified export popup: pick a format (CSV, Excel, PDF, or All) and where to
save, in one place, instead of a separate button per format.

Replaces MainWindow's old separate "Export to CSV" / "Export to Excel"
buttons and their individual filedialog.asksaveasfilename() calls. Since
"All" needs to write up to three files at once (one per format), this
window asks for a save FOLDER (defaulting to config.EXPORT_DIRECTORY, the
app's normal export location) rather than a single filename - the actual
filenames are generated by ExportService.default_filename() so a single
choice here works whether one format or all three are requested.
"""
from tkinter import StringVar
from tkinter import ttk, filedialog

from ui.widgets.popup import Popup
from config import EXPORT_DIRECTORY

_FORMAT_OPTIONS = [
    ("csv", "CSV"),
    ("excel", "Excel"),
    ("pdf", "PDF"),
    ("all", "All (CSV + Excel + PDF)"),
]


class ExportWindow(Popup):
    def __init__(self, parent, theme, on_export):
        """on_export: callable(format_key: str, folder: str) -> None
        format_key is one of 'csv', 'excel', 'pdf', 'all'."""
        super().__init__(parent, "Export", theme, width=420, height=320, custom_titlebar=False)
        self.on_export = on_export
        self.content.grid_columnconfigure(0, weight=1)

        ttk.Label(self.content, text="Export format: ", anchor="center").grid(
            row=0, column=0, pady=(10, 2), sticky="ew"
        )
        self._format_var = StringVar(value=_FORMAT_OPTIONS[0][0])
        format_frame = ttk.Frame(self.content)
        format_frame.grid(row=1, column=0, pady=5)
        for key, label in _FORMAT_OPTIONS:
            ttk.Radiobutton(format_frame, text=label, value=key, variable=self._format_var).pack(
                anchor="w", pady=2
            )

        ttk.Label(self.content, text="Save to folder: ", anchor="center").grid(
            row=2, column=0, pady=(15, 2), sticky="ew"
        )
        self._folder_var = StringVar(value=EXPORT_DIRECTORY)
        folder_row = ttk.Frame(self.content)
        folder_row.grid(row=3, column=0, pady=5, padx=10, sticky="ew")
        folder_row.grid_columnconfigure(0, weight=1)
        folder_entry = ttk.Entry(folder_row, textvariable=self._folder_var, justify="center")
        folder_entry.grid(row=0, column=0, sticky="ew", padx=(0, 5))
        ttk.Button(folder_row, text="Browse...", command=self._browse).grid(row=0, column=1)

        submit_btn = ttk.Button(self.content, text="Export", command=self._submit, width=12)
        submit_btn.grid(row=4, column=0, pady=20)
        self.bind("<Return>", lambda e=None: submit_btn.invoke())
        self.center_over_parent()

    def _browse(self):
        chosen = filedialog.askdirectory(initialdir=self._folder_var.get() or EXPORT_DIRECTORY, title="Choose export folder")
        if chosen:
            self._folder_var.set(chosen)

    def _submit(self):
        folder = self._folder_var.get().strip()
        if not folder:
            self.notify("warning", "Input Error", "Please choose a folder to export to.")
            return
        self.destroy()
        self.on_export(self._format_var.get(), folder)